# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='response',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='pub_date',
        ),
    ]
