# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20170925_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='text',
            new_name='response',
        ),
    ]
